pysatSpaceWeather/instruments/__init__.py, pysatSpaceWeather/instruments/methods/__init__.py, pysatSpaceWeather/instruments/methods/ace.py, pysatSpaceWeather/instruments/sw_ace.py, pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/tests/test_instruments.py
This reverts commit 17751cb794b0e048f564fff8643f93b61b80b2bd and addresses #13
=> Revert "STY: Cleanup"

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md
Added missing community documents, addressing issue #4.
=> Community docs

.travis.yml, CHANGELOG.md, MANIFEST.in, requirements.txt, setup.cfg, setup.py, test_requirements.txt
Simplified the setup and testing structure.  Addresses #17 
Will be tested on travis
=> Setup update

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Fixed spelling in templates.
Addresses #24 
This has been tested by copying the template text into Written? Kitten! and using their spell checker.
* Operating system: plain format text box
* Version number: N/A
* Any details about your local setup that are relevant: kittens
- [N/A] Make sure you are merging into the ``develop`` (not ``master``) branch
=> MAINT: fixed spelling

pysatSpaceWeather/instruments/sw_dst.py
Updated the import order and docstrings.  Addresses today's discussion about logger, which is already done the most efficient way for this project.
- Style update
Ran local unit tests
=> MAINT: flake8 and docs

.github/pull_request_template.md, .travis.yml, test_requirements.txt
Add CI testing for docs.
Addresses #23 
This will be tested by travis.
* Operating system: Linux
=> TST: add CI doc testing

.zenodo.json
Removed 'access_right' and 'resource_type' keys.
Addresses #29 
Can only be tested on package release.
=> BUG: remove unneeded keys

pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/kp_ap.py
Improves comments and organization of methods to accurately scope their use.
Running existing unit tests
* Any details about your local setup that are relevant: pysat at https://github.com/pysat/pysat/pull/654
=> Custom style update

README.md
Adds badge to readme page for Github Actions.
n/a
=> DOC: update badge

README.md, docs/installation.rst, docs/overview.rst
Cleans up some typos and whitespace in the docs.
visual inspection
=> STY: typos

CHANGELOG.md, README.md, docs/installation.rst
Adds PyPi to the installation instructions, addresses #38 
Clicking on links!
=> PyPi installation update

CHANGELOG.md, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/tests/test_methods_f107.py
Moves remaining instrument support functions from the Instrument modules to the appropriate `methods` module.  Addresses inconsistency identified when updating local pysatSpaceWeather dependent routines.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Updated unit tests.
* Any details about your local setup that are relevant: develop branch on pysat
=> Method reorg

.github/workflows/main.yml, pysat_requirements.txt
Addresses # (issue)
- Original:Testing against pysat v3.0.1RC
- Now: Updates against latest pysat release version. Removes any temporary tweaks for RC check.
- Testing expanded to more OS platforms!
- Release Candidate Testing
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce the problem and the solution. Including images
or test files is frequently very useful.  Please also list any relevant details
for your test configuration.
Testing against package as is.
* Operating system: GitHub Actions
* Version number: Python 3.7, 3.8, 3.9
release checklist on the …
=> TST: Test against pysat v3.0.1RC

CHANGELOG.md, pysatSpaceWeather/instruments/methods/kp_ap.py, pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/tests/test_methods_kp.py
Addresses #65 by adding coverage or removing uncovered lines in most cases.  Remaining uncovered lines are in areas that are difficult to reach as they rely on external failures, et cetera.
Introduced new unit tests and ran them locally
=> Extended unit tests

pysatSpaceWeather/instruments/ace_sis.py, pysatSpaceWeather/instruments/methods/ace.py, test_requirements.txt
Addresses #72
Updates tag/inst_inst/data_path standards per group projects, https://github.com/orgs/pysat/projects/4/views/1 and https://github.com/orgs/pysat/projects/3
- Standards update
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce the problem and the solution. Including images
or test files is frequently very useful.  Please also list any relevant details
for your test configuration.
- Unit test suite
* Operating system: MacOS
=> Tag update

.github/workflows/docs.yml, .github/workflows/main.yml, CHANGELOG.md
Updated the GitHub actions used in the CI yamls.
Upon completion, the Actions should not have any deprecation warnings.
* Operating system: GitHub Actions
* Version number: Python Any
=> Update CI action versions

.github/workflows/main.yml
Numpy install was being overwritten with latest version in NEP29 tests, fixing.
Runs on CI
* Operating system: GitHub Actions
* Version number: Python 3.8
=> BUG: fixed numpy install

CHANGELOG.md, docs/supported_instruments.rst, pysatSpaceWeather/instruments/__init__.py, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/gfz.py, pysatSpaceWeather/instruments/methods/lisird.py, pysatSpaceWeather/instruments/sw_ap.py, pysatSpaceWeather/instruments/sw_apo.py, pysatSpaceWeather/instruments/sw_cp.py, pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_hpo.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/instruments/sw_polarcap.py, pysatSpaceWeather/instruments/sw_ssn.py, pysatSpaceWeather/instruments/sw_stormprob.py, pysatSpaceWeather/tests/test_methods_f107.py
Addresses #90 by adding the new GFZ Hpo and apo indices.  Added a general download function for GFZ data and expanded the existing F10.7 and SSN instruments to include the GFZ data as options.
```
import pysat
import pysatSpaceWeather as py_sw
hpo = pysat.Instrument(inst_module=py_sw.instruments.sw_hpo, tag='now', inst_id='30min')
stime = dt.datetime(2014, 3, 26)
hpo.download(start=stime)
hpo.load(date=stime)
hpo.data[:10]
```
Yields
```                      Hp30
2014-03-26 00:00:00  3.667
2014-03-26 00:30:00  4.667
2014-03-26 01:00:00  3.333
2014-03-26 01:30:00  3.333
2014-03-26 02:00:00  3.000
2014-03-26 02:30:00 …
```
=> Expanded instruments to include all GFZ indices

.github/workflows/pysat_rc.yml, CHANGELOG.md, pyproject.toml, pysatSpaceWeather/instruments/methods/kp_ap.py
Remove unneeded kwargs from the instrument instantiation.
Ran unit tests.
=> pysat RC 3.2.0 fixes

.github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/pip_rc_install.yml, .github/workflows/pysat_rc.yml, .readthedocs.yml, CHANGELOG.md, README.md, docs/installation.rst, pyproject.toml
Bumps the python version support and the GitHub action versions used in CI.
Needs to be tested on CI.
- [N/A] Make sure you are merging into the ``develop`` (not ``main``) branch
=> MAINT: Python12 version bump
