pysatSpaceWeather/tests/test_instruments.py
Updates syntax for instrument tests inherited from `pysat` as part of pysat/pysat#552.
- End-to-end instrument tests now iterate over a list of `dict` objects containing info to create an instrument
- `pytest.mark` statements updated accordingly
- `package` renamed as `inst_loc`
Passing locally with the `tst/inst_test_class_update` branch of pysat. Expected to fail on Travis until pysat/pysat#552 is merged.
NOTE: local tests of combine methods are failing in python 3.8.  These are unrelated to the changes above.
=> MAINT: update test_inst_class

pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_kp.py
Addresses pysat/pysat#473, test with pysat/pysat#556
Updates use of `sat_id` to `inst_id`.
Passing locally with the `break/inst_id` branch of pysat.  Expected to fail on Travis until pysat/pysat#556 is merged.
=> MAINT: use inst_id

pysatSpaceWeather/instruments/__init__.py, pysatSpaceWeather/instruments/methods/__init__.py, pysatSpaceWeather/instruments/methods/ace.py, pysatSpaceWeather/instruments/sw_ace.py
Added new instrument, sw_ace, which handles the four different real-time data sets available from ACE.  This differs from the science-level ACE data in its availability, resolution, and data products.
This branch has been tested locally and all ACE related tests pass.  New unit tests have not been added, as no special functions were created.  Method routines deal with assigning acknowledgements and references.
To try this out to see how it works well:
```
import pysat
import pysatSpaceWeather as pysat_sw
stime = dt.datetime(2009,1,1)
amag = pysat.Instrument(inst_module=pysat_sw.instruments.sw_ace, tag='hist', sat_id='mag')
amag.download(start=stime, stop=stime)
amag.load(date=stime)
print(amag.data.iloc[:3])                                              
jd    sec …
```
=> ENH: added new instrument, sw_ace

CHANGELOG.md, pysatSpaceWeather/instruments/sw_ace.py, pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/tests/test_sw.py
Fixed the issues introduced by upstream changes.  Addresses issues #9, #10, and #11 
To test, run unit tests.
```
=============================== warnings summary ===============================
pysatSpaceWeather/tests/test_sw.py::TestSWKp::test_convert_ap_to_kp_middle
/Users/aburrell/Programs/Git/pysatSpaceWeather/pysatSpaceWeather/tests/test_sw.py:152: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
self.testInst['3hr_ap'][8] += 1
-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 136 passed, 19 skipped, 1 warning in 25.10s ==================
```
Ran on OSX Mojave, python 3.7.
=> BUG: pysat upstream updates

pysatSpaceWeather/tests/test_instruments.py, pysatSpaceWeather/tests/test_methods_f107.py, pysatSpaceWeather/tests/test_methods_kp.py
Updates package for changes in https://github.com/pysat/pysat/pull/637.
Found a few instances of `pysat.data_dir` in the unit tests.
Ran unit tests on local machine with the `pysat_params` branch.
* Operating system: MacOS
* Version number: Python 3.8
=> ENH: Update to latest pysat

CHANGELOG.md, pysatSpaceWeather/instruments/sw_f107.py
Addresses #52 by fixing the forced year-long loading of preliminary F10.7 data.
```
import pysatSpaceWeather
import pysat
f107_prelim = pysat.Instrument(inst_module=pysatSpaceWeather.instruments.sw_f107, tag='prelim', update_files=True)
f107_prelim.download(start=dt.datetime(2020, 1, 1), stop=dt.datetime(2020, 2, 1))
f107_prelim.load(2020, 1)
print(f107_prelim.data)
f107  ssn  ss_area  new_reg  ...  x_flare o1_flare  o2_flare  o3_flare
2020-01-01    72    0        0        0  ...        0        0         0         0
[1 rows x 12 columns]
```
* Operating system: OSX Mojave
* Any details about your local setup that are relevant: pysat develop …
=> F107 prelim update

CHANGELOG.md, pysatSpaceWeather/instruments/methods/ace.py, pysatSpaceWeather/instruments/methods/dst.py, pysatSpaceWeather/instruments/sw_dst.py
Addresses #56 
Fixed multi-day data loading issue. Also improved efficiency when loading multiple days, plus, I added metadata.
```
start_date = dt.datetime(2001, 1, 1)
end_date = dt.datetime(2001, 12, 31)
dst = pysat.Instrument('sw', 'dst')
dst.load(date=start_date, end_date=end_date)
dst['dst'].plot(title=dst.meta['dst', dst.meta.labels.name], 
ylabel=dst.meta['dst', dst.meta.labels.units])
```
* Operating system: Mac OS 10.15.4
* Version number: Python 3.8.3
=> Dst update

CHANGELOG.md, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/kp_ap.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/tests/test_methods_f107.py, pysatSpaceWeather/tests/test_methods_kp.py, requirements.txt, setup.cfg
Addresses #74, #75, and #76.  Also removes the future 'use_header' deprecation warning and the pandas "set value with copy" warning.
Ran unit tests locally with main and develop branches of pysat.
=> Deprecation update

CHANGELOG.md, pysatSpaceWeather/instruments/sw_f107.py
Addresses # (issue)
LASP updated their F10.7 data format which broke current code. This is a minimal bug fix.
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce the problem and the solution. Including images
or test files is frequently very useful.  Please also list any relevant details
for your test configuration.
- Tested locally by downloading and loading 'historic' data from `sw_f107`
* Operating system: MacOS …
=> BUG: Generalize f107 historic data check

CHANGELOG.md, pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/tests/test_instruments.py, pysatSpaceWeather/tests/test_methods_ace.py, pysatSpaceWeather/tests/test_methods_f107.py, pysatSpaceWeather/tests/test_methods_general.py, pysatSpaceWeather/tests/test_methods_kp.py
Updates syntax to keep up with deprecations
- Updated syntax for pysat instrument testing suite
- `_test_download_ci`
- new testing class
- `use_header=True`
- Remove deprecated pytest syntax (backwards support for nose)
- Removed deprecated pandas syntax (iteritems)
pytest suite
* Operating system: Mac OS Monterrey
* Version number: Python 3.8.11
* pysat develop
=> MAINT: pysat test suite and deprecations (pytest, pandas)

CHANGELOG.md, pysatSpaceWeather/instruments/sw_f107.py
Updated the allowed fill value types for F10.7 'daily' and 'prelim' metadata. Addresses #91.
```
import pysat
f107 = pysat.Instrument('sw', 'f107', tag='prelim')
f107.load(2014, 25, use_header=True)
f107['goes_bgd_flux']
```
Yeilds:
```
2014-01-25    *
Name: goes_bgd_flux, dtype: object
```
And no warnings are raised.
* Version number: Python 3.8
=> BUG: updated fill value type

CHANGELOG.md, docs/supported_instruments.rst, pysatSpaceWeather/instruments/__init__.py, pysatSpaceWeather/instruments/methods/__init__.py, pysatSpaceWeather/instruments/methods/auroral_electrojet.py, pysatSpaceWeather/instruments/methods/lasp.py, pysatSpaceWeather/instruments/sw_ae.py, pysatSpaceWeather/instruments/sw_al.py, pysatSpaceWeather/instruments/sw_au.py, pysatSpaceWeather/instruments/sw_dst.py, pysatSpaceWeather/tests/test_methods_ae.py
Addresses #70 by adding the remaining prediction data sets.
```
import pysat
import pysatSpaceWeather as py_sw
al = pysat.Instrument(inst_module=py_sw.instruments.sw_al, tag='lasp', use_header=True)
al.download()  # always get the current data for today's date
al.load(date=pysat.utils.time.today())
print(al)
```
Will have a time series with the desired auroral electrojet index (AL, AU, and AE were all added). …
=> LASP auroral index prediction data

.github/workflows/pip_rc_install.yml, .github/workflows/pysat_rc.yml, CHANGELOG.md, pysatSpaceWeather/tests/test_methods_general.py, test_requirements.txt
Updates RC testing for latest pysat release candidate: https://github.com/pysat/pysat/pull/1116
Adds a dispatch workflow to test installing the pysatSpaceWeather RC from pip.
Fixes a bug in the unit tests that appears with the new RC.
Imposes an upper limit to `hacking` to keep new style changes from being checked.
Running `pysat_rc.yml` in the actions tab: https://github.com/pysat/pysatSpaceWeather/actions/workflows/pysat_rc.yml
* Github Actions
=> MAINT: update RC tests

CHANGELOG.md, pysatSpaceWeather/instruments/ace_epam.py, pysatSpaceWeather/instruments/ace_mag.py, pysatSpaceWeather/instruments/ace_sis.py, pysatSpaceWeather/instruments/ace_swepam.py, pysatSpaceWeather/instruments/methods/ace.py
Addresses the pysat changes introduced in https://github.com/pysat/pysat/pull/1129 by adding the new cleaning test attribute.  This attribute may be present with an older version of pysat, it just won't do anything.
Ran unit tests locally with the `clean_warning` pysat branch.
* Any details about your local setup that are relevant: pysat https://github.com/pysat/pysat/pull/1129
=> TST: updated ACE test attributes

CHANGELOG.md, docs/conf.py, docs/index.rst, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/kp_ap.py, pysatSpaceWeather/tests/test_methods_ace.py, pysatSpaceWeather/tests/test_methods_f107.py, pysatSpaceWeather/tests/test_methods_general.py, pysatSpaceWeather/tests/test_methods_kp.py
Addresses #117 and adds TODO statements for issue #131 to reduce user warnings after the next pysat release.
Ran unit tests locally
=> MAINT: support for pysat behaviour changes

.github/workflows/main.yml, .github/workflows/pysat_rc.yml, CHANGELOG.md, docs/conf.py, docs/supported_instruments.rst, pyproject.toml, pysatSpaceWeather/instruments/ace_sis.py, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/gfz.py, pysatSpaceWeather/instruments/methods/kp_ap.py, pysatSpaceWeather/instruments/methods/swpc.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/tests/test_methods_kp.py
Avoid certificate expiration by using the `verify` flag set to False.
Addresses an issue identified at APL, where their certificate had expired.
Unit tests
=> BUG: avoid certificate experation

CHANGELOG.md, pysatSpaceWeather/instruments/ace_epam.py, pysatSpaceWeather/instruments/ace_mag.py, pysatSpaceWeather/instruments/ace_sis.py, pysatSpaceWeather/instruments/ace_swepam.py, pysatSpaceWeather/instruments/methods/ace.py, pysatSpaceWeather/instruments/sw_ap.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/instruments/sw_flare.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/instruments/sw_mgii.py, pysatSpaceWeather/instruments/sw_polarcap.py, pysatSpaceWeather/instruments/sw_sbfield.py, pysatSpaceWeather/instruments/sw_ssn.py, pysatSpaceWeather/instruments/sw_stormprob.py, pysatSpaceWeather/tests/test_methods_gfz.py
Addresses #143 by replacing `utcnow` with `now` calls.
Ran unit tests locally
=> Datetime update

CHANGELOG.md, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/kp_ap.py, pysatSpaceWeather/tests/test_methods_f107.py, pysatSpaceWeather/tests/test_methods_kp.py
Addresses #142 by removing the assumption that all instruments will have downloaded files that can be queried.
First, go and delete any data present in these instrument directories.
```
import pysat
import pysatSpaceWeather as pysw
pred = pysat.Instrument(inst_module=pysw.instruments.sw_kp, tag='prediction')
rec = pysat.Instrument(inst_module=pysw.instruments.sw_kp, tag='recent')
start = dt.datetime(2023, 12, 1)
stop = dt.datetime(2024, 2, 1)
kp = pysw.instruments.methods.kp_ap.combine_kp(now, pred, start=start, stop=stop)
forecast = pysat.Instrument(inst_module=pysw.instruments.sw_f107, tag='forecast')
daily = pysat.Instrument(inst_module=pysw.instruments.sw_f107, …
```
=> Combine data bugfix

CHANGELOG.md, README.md, docs/installation.rst, pyproject.toml, pysatSpaceWeather/instruments/methods/f107.py, pysatSpaceWeather/instruments/methods/kp_ap.py, pysatSpaceWeather/instruments/sw_kp.py, pysatSpaceWeather/tests/test_instruments.py, pysatSpaceWeather/tests/test_methods_ace.py, pysatSpaceWeather/tests/test_methods_f107.py, pysatSpaceWeather/tests/test_methods_general.py, pysatSpaceWeather/tests/test_methods_kp.py
Addresses #136, #131, and #101 by removing support for deprecated features and updating the minimum supported pysat version to 3.2.0+.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Ran unit tests locally
=> Maintenance for V0.2.0 release

CHANGELOG.md, docs/supported_instruments.rst, pysatSpaceWeather/instruments/__init__.py, pysatSpaceWeather/instruments/methods/__init__.py, pysatSpaceWeather/instruments/methods/norp.py, pysatSpaceWeather/instruments/norp_rf.py, pysatSpaceWeather/instruments/sw_f107.py, pysatSpaceWeather/tests/test_data/TYKW-NoRP_dailyflux.txt, pysatSpaceWeather/tests/test_methods_norp.py
Addresses #119 by adding the daily solar radio fluxes at different wavelengths from the NoRP database.
```
import pysat
import pysatSpaceWeather as pysw
rf = pysat.Instrument(inst_module=pysw.instruments.norp_rf, tag='daily')
rf.download(start=dt.datetime(1951, 1, 1), stop=rf.today())
rf.load(date=dt.datetime(2021, 1, 3), end_date=dt.datetime(2021, 2, 5))
```
This will load data for the desired period and have 4 different variables.
Also added unit tests.
If this is a release …
=> F30 Instrument

.zenodo.json, CHANGELOG.md, docs/conf.py, pyproject.toml, pysatSpaceWeather/instruments/methods/swpc.py
Completes milestone 0.2.0 by bringing changes from RC back into develop.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Unit and integration tests
=> V0.0.2rc develop update

.github/workflows/main.yml, CHANGELOG.md, README.md, docs/installation.rst, pyproject.toml
Cycles Python support for updated operational environment.
Verified ops configuration.
* Operating system: Red Hat
=> Ops update

pysatSpaceWeather/instruments/methods/f107.py
Change the location of the index evaluation to work correctly.
Ran operational file code, which identified the bug.
* Operating system: OS X Sonoma
=> BUG: fixed index evaluation
